Repository edgexfoundry/go-mod-core-contracts, pull requests merged in 2019-05, with the labels that each got.

#84 Added AddBytes & MarshalEvent methods to EventClient
  clients/coredata/event.go
  clients/coredata/event_test.go
  clients/coredata/reading_test.go
Labels: edinburgh, enhancement

#94 Set Description During DeviceProfile.Unmarshal()
  models/deviceprofile.go
Labels: bug

#97 Removing Required Device Name from Reading
  models/reading.go
  models/reading_test.go
Labels: enhancement

#99 Extend EventClient to Allow "Mark Pushed by Checksum"
  clients/coredata/event.go
  clients/coredata/event_test.go
Labels: edinburgh, enhancement

#106 Registration.Filter Incorrect Marshaling as 'filter.go'
  models/registration.go
Labels: bug, edinburgh

#107 semver(master): 0.1.0
  master
Labels: hold
